{
  lib,
  config,
  pkgs,
  ...
}:
{
  options.greenery.server.auth.enable = lib.mkEnableOption "2FAuth Docker Service";

  config = lib.mkIf (config.greenery.server.auth.enable && config.greenery.server.enable) {
    
    # Agenix secret
    age.secrets.secret3.file = ../../secrets/secret3.age;

    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    virtualisation.oci-containers.containers."2fauth" = {
      image = "2fauth/2fauth:latest";
      environmentFiles = [config.age.secrets.secret3.path];
      environment = {
        "APP_ENV" = "production";
        "APP_URL" = "https://auth.onca-ph.ts.net";
        "ASSET_URL" = "https://auth.onca-ph.ts.net";
        "DB_CONNECTION" = "sqlite";
        "DB_DATABASE" = "/srv/database/database.sqlite";
      };
      volumes = [
        "/var/lib/2fauth:/2fauth:rw"
      ];
      ports = [
        "8000:8000/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=2fauth"
        "--network=auth_default"
      ];
    };
    systemd.services."docker-2fauth" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "no";
      };
      after = [
        "docker-network-auth_default.service"
      ];
      requires = [
        "docker-network-auth_default.service"
      ];
      partOf = [
        "docker-compose-auth-root.target"
      ];
      wantedBy = [
        "docker-compose-auth-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-auth_default" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f auth_default";
      };
      script = ''
        docker network inspect auth_default || docker network create auth_default
      '';
      partOf = [ "docker-compose-auth-root.target" ];
      wantedBy = [ "docker-compose-auth-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-auth-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
